name: CD-持续交付
run-name: CD-${{github.actor}}-${{github.ref_name}}-${{github.event.head_commit}}

on:
    push:
        paths-ignore:
            - ".github/**" # 忽略掉GitHub目录
        
        branches:
            - main # 只触发main分支

    pull_request:
        paths-ignore:
            - ".github/**"

        branches:
            - main

    workflow_call:

jobs:
    build:
        name: 打包
        environment: development
        runs-on: ubuntu-latest
        steps:
            - name: build
              run: |
                echo build
                echo "mode ${{vars.MODE}}"
            
            
    delivery:
        name: 提交assetbendle
        environment: 
            name: development
            url: baidu.com

        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: delevery
              run: |
                echo upload assetbundle
                echo "asset server ${{vars.ASSET_SERVER}}"
