name: CI
run-name: CI-${{github.actor}}-${{github.ref_name}}-${{github.event.head_commit}}

on:
    push:
        paths-ignore:
            - ".github/**" # 忽略掉GitHub目录

    pull_request:
        paths-ignore:
            - ".github/**"

    workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              run:  echo "Checkout"

            - name: Setup Python
              run: echo "Setup Python"

            - name: Run Test
              run: echo "Run Test"

